### ISSUE TITLE
"Materials" Section on the Course page, to which instructors could upload documents

### ISSUE THREAD

**Issue by MindImpMatt** [maltyeva/mindimp-pg#29] opened 2015-03-06 05:55 UTC
I know we have a space to upload a syllabus, so maybe we could also have a space for other course materials? If the instructor has a Powerpoint presentation, for example, to share with students, he could upload it here for them to see.

**Comment by maltyeva** [comment] 2015-03-27 05:11
I think this is a duplicate of #60 which is being worked on now. merging.

**Closed** 2015-03-27 05:12 UTC
Labels: feature
